databases:
  - type: mongo
    enabled: true
    name: "spark-poc"
    host: "http://localhost"
    port: 27017
    username: ""
    password: ""

  - name: redis
    type: redis
    enabled: true
    host: "localhost"
