databases:
  - name: mongo
    enabled: false
    name: "spark-poc"
    host: "http://localhost"
    port: 27017
    username: ""
    password: ""

  - name: redis
    enabled: true
    host: "localhost"
